version: '3'
services:
  workshop.api:
    build: ./api
    ports:
     - 80:80
    depends_on:
     - workshop.postgres
     - workshop.elasticsearch
  workshop.postgres:
    image: postgres:alpine
    volumes:
     - workshop.postgres.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
  workshop.elasticsearch:
    build: ./elasticsearch
    volumes:
      - workshop.elasticsearch.data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  workshop.kibana:
    build: ./kibana
    depends_on:
     - workshop.elasticsearch
    ports:
      - 5601:5601

volumes:
  workshop.postgres.data:
  workshop.elasticsearch.data: